# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: <%= Rails.application.credentials.neon[:development_database_url] %>

test:
  <<: *default
  url: <%= Rails.application.credentials.neon[:development_database_url] %>

production:
  <<: *default
  url: <%= Rails.application.credentials.neon[:production_database_url] %>

queue:
  <<: *default
  url: <%= Rails.application.credentials.neon[:development_database_url] %>

cache:
  <<: *default
  url: <%= Rails.application.credentials.neon[:development_database_url] %>
